#! /usr/bin/python
# coding: utf-8
import sys

"""

made by ch4n3
to connect to me, send email to chaneyoon[at]gmail[dot]com
blog : http://chaneyoon.tistory.com/
wargame : http://ch4n3.dothome.co.kr/

"""

"""
### assignment
arp_spoof <interface> <sender ip 1> <target ip 1> [<sender ip 2> <target ip 2>...]

"""

if __name__ == "__main__":
	
	# check argc
	if len(sys.argv) < 4:
		print "[*] arp_spoof <interface> <sender ip> <target ip>"
		sys.exit(1);
		
	# set network interface 
	interface = sys.argv[1]

	print "[*] your interface : {0}".format(interface)




